---
title: HW1.4
author: RJ Cass
format: pdf
---

```{r}
suppressPackageStartupMessages(library('ggplot2'))
suppressPackageStartupMessages(library('dplyr'))
suppressPackageStartupMessages(library('car'))
suppressPackageStartupMessages(library('lmtest'))
suppressPackageStartupMessages(library('multcomp'))
data <- read.table("BirthWeights.txt", sep = " ", header = TRUE, as.is = FALSE)
```

# HW 1.1

### 1. 

```{r}
ggplot(data, aes(x=Mage, y=BirthWeight)) + 
  geom_point() +
  geom_smooth(method="lm", se=FALSE)
```


### 2. 

```{r}
ggplot(data, aes(x=Race, y=BirthWeight)) + 
  geom_boxplot()
```


### 3. 

```{r}
ggplot(data, aes(x = Gage, y = BirthWeight, color = Race)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE) + 
  labs(x = 'Gestational Age', y = "Weight at Birth (g)")
```

### 4. 

```{r}
data %>%
  group_by(Gen) %>%
  summarise(correlation = cor(BirthWeight, Mage))
```


### 5. 

```{r}
GGally::ggpairs(data)
```

# HW 2.2

### 1. 

```{r}
# Design matrix
X <- model.matrix(~ Mage + Gage + Race + Gen, data = data)
y <- matrix(data[, 1], ncol = 1)

# beta = (X'X)^(-1)*X'y
beta <- solve(t(X) %*% X) %*% t(X) %*% y

# S2
n <- nrow(X)
p <- ncol(X)
resids <- y - (X %*% beta)
S2 <- sum(resids^2) / (n-p)

lm <- lm(BirthWeight ~ ., data = data)

beta
lm$coefficients

S2
summary(lm)$sigma^2
```

### 2. 

```{r}
# Manual vs. LM
table(round(X %*% beta, 3) == round(lm$fitted.values, 3))
```

### 3. 

```{r}
# Manual vs. LM
table(round(y - X%*%beta, 3) == round(lm$residuals, 3))
```

# HW 1.3

### 1. 

```{r}
mod <- lm(BirthWeight ~ Mage + Gage, data = data)
avPlots(mod)
```

### 2. 

```{r}
mod <- lm(BirthWeight ~ ., data = data)
hist(rstandard(mod), freq = FALSE, breaks = seq(from = -3.5, to = 3.5, by = .2))
curve(dnorm(x), add = TRUE, col = 'red')

ks.test(rstandard(mod), "pnorm")
```

### 3. 

```{r}
bp <- bptest(mod)
p_val <- bp$p.value
p_label <- paste("BP Test p-value:", format.pval(p_val, digits = 3))
plot(mod$fitted.values, mod$residuals)
mtext(p_label, side = 3, line = -1, font = 2, col = 'blue')
```

### 4. 

```{r}
summary(mod)$r.squared
```

### 5. 

```{r}
cross_validate <- function(fold_num){
    cv_data <- data[folds == fold_num, ]
    cv_mod <- lm(BirthWeight ~ ., data = cv_data)
    rmse <- sqrt(mean(cv_mod$residuals^2))
    rmse
}

set.seed(1337)
K <- 20
folds <- rep(1:K, length = nrow(data)) %>% #Rep K folds n times
    sample()
## Using sapply()
rmse_results <- sapply(1:K, FUN=cross_validate)

## Plot the Results
ggplot() + geom_histogram(mapping=aes(x=rmse_results))
```

# HW 1.4

### 1

$SE(\beta_{Gage}) = s \sqrt{a'(X'X)^{-1}a}$

```{r}
summary(mod)
confint(mod)

a <- t(matrix(c(0,0,1,0,0,0,0)))
s <- 281.6 # Residual Standard Error from summary
se_gage <- as.numeric(s * sqrt(a%*%solve(t(X)%*%X)%*%t(a)))
est_gage <- mod$coefficients[3]
gage_int <- est_gage + c(-1, 1)*qt(.975, df=nrow(data)-ncol(X))*se_gage

gage_int
```

### 2

Q = number of variables being tested

$F = \frac{(R^2_{All} - R^2_{Red})/Q}{(1-R^2_{All})/(n-P-1)}$

```{r}
Q <- 6
R2_all <- .6065
R2_red <- 0

F_stat_manual <- ((R2_all - R2_red)/Q)/((1-R2_all)/(nrow(X) - 7-1))
F_stat_R <- summary(mod)$fstatistic[1]
```

Manual F-stat: `r F_stat_manual`
R F-stat: `r F_stat_R`

The difference is just because I rounded the R2 value in the manual case. 

### 3

```{r}
int_mod <- lm(BirthWeight ~ . + Gage:Gen, data = data)
anova(mod, int_mod)
```

Large p-value, so we accept the null-hypothesis that there is no difference between the models, meaning the interaction is not significant

### 4

```{r}
hyp_diff <- glht(mod, linfct="5*Mage - Racehisp + GenMale == 0")
confint(hyp_diff)
```

### 5

```{r}
new_data <- data.frame(Mage = 25, Gage = 30, Race = "white", Gen = "Female")
predict(mod, newdata = new_data, interval = "prediction", level = 0.75)
```