---
title: HW0 LA Review in R
author: RJ Cass
format: pdf
---


# 1. 

```{r}
A <- matrix(data = c(8, 6, 6, 8), nrow = 2, byrow = TRUE)
B <- matrix(data = c(1, 8, 3, 5), nrow = 2, byrow = TRUE)
```

### (a)

```{r}
A+B
```

### (b)

```{r}
A-B
```

### (c)

```{r}
A%*%B
```

### (d)

```{r}
B%*%A
```

# 2. 

```{r}
A <- matrix(data = c(3, 1, 3, 7), ncol = 2, byrow = TRUE)
B <- matrix(data = c(2, 2, 10, 4, 7, 3), ncol = 3, byrow = TRUE)
```

### (a)

```{r}
#| error: true
A+B
```

### (b)

```{r}
#| error: true
A-B
```

### (c)

```{r}
A%*%B
```

### (d)

```{r}
#| error: true
B%*%A
```

# 3. 

```{r}
A <- matrix(data = c(4, 3, 11, 2), ncol = 2, byrow = TRUE)
B <- matrix(data = c(2, 8, 8, 12), ncol = 2, byrow = TRUE)
C <- matrix(data = c(1, 1, 2, 1, 3, 5, 2, 5, 8), ncol = 3, byrow = TRUE)
D <- matrix(data = c(4, 4, 2, 4), ncol = 2, byrow = TRUE)
```

### (a)

```{r}
t(A)
isSymmetric(A)
```

### (b)

```{r}
t(B)
isSymmetric(B)
```

### (c)

```{r}
t(C)
isSymmetric(C)
```

### (d)

```{r}
t(D)
isSymmetric(D)
```

# 4.

### (a)

```{r}
solve(A)
```

### (b)

```{r}
solve(B)
```

### (c)

```{r}
solve(A%*%B)
```

### (d)

```{r}
solve(B) %*% solve(A)

(solve(B) %*% solve(A)) == (solve(A%*%B))
```

Funnily enough, R thinks the results are different (my guess is some very minor numeric computation error in cell [1,1]), but yes, just looking at the two results you can see they are equal. 

# 5. 

```{r}
A <- matrix(data = c(4, 3, 11, 2), ncol = 2, byrow = TRUE)
B <- matrix(data = c(2, 8, 4, 0, 5, 333, 1, 0, 1, 1, 7, 0, 6, 10, 423, 0), ncol = 4, byrow = TRUE)
C <- matrix(data = c(1, 1, 2, 1, 3, 5, 2, 5, 8), ncol = 3, byrow = TRUE)
D <- matrix(data = c(4, 0, 0, 2), ncol = 2, byrow = TRUE)
```


### (a)

```{r}
det(A)
```

### (b)

```{r}
det(B)
```

### (c)

```{r}
det(C)

c_transpose <- t(C)
det(c_transpose)
```

Verified that $|C^{\top}| = |C|$

### (d)

```{r}
det(D)

d_inv <- solve(D)
det(d_inv)
```

Verified that $|D^{-1}| = 1/|D|$

# 6. 

```{r}
A <- matrix(data = c(7, 2, 5, 8, -3, 4, 0, 2, 9, 3, 6, 5, 3, 1, 2, 1), ncol = 4, byrow = TRUE)

A11 <- A[1:2, 1:3]
A12 <- A[1:2, 4]
A21 <- A[3:4, 1:3]
A22 <- A[3:4, 4]

A11
A12
A21
A22
```